name: homework
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  cupertino_icons: ^1.0.1
  get: ^3.25.4
  cached_network_image: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  retrofit_generator: ^1.3.7
  build_runner: any
  json_serializable: any

flutter:
  uses-material-design: true